/* ==========================================================================
   EXPORT — PNG Screenshot + Cisco IOS Config + 2D SVG Topology
   ========================================================================== */

/* ---------- Yordamchi: fayl yuklab olish ---------- */
function downloadBlob(filename, content, type = 'text/plain') {
  const blob = new Blob([content], { type });
  const url  = URL.createObjectURL(blob);
  const a    = Object.assign(document.createElement('a'), { href: url, download: filename });
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/* ==========================================================================
   1. PNG Screenshot (Three.js renderer orqali)
   ========================================================================== */
function captureSceneSnapshot() {
  // preserveDrawingBuffer: true bo'lishi kerak; agarda yo'q bo'lsa ogohlantirish
  try {
    renderer.render(scene, camera);
    const dataUrl = renderer.domElement.toDataURL('image/png');
    if (dataUrl === 'data:,') {
      toast('⚠️ Screenshot olish uchun renderer.preserveDrawingBuffer=true kerak');
      return;
    }
    downloadBlob('lan3d_screenshot.png', dataUrl); // base64 DataURL download
    // Ma'lumot URL uchun maxsus yondashuv
    const a    = document.createElement('a');
    a.href     = dataUrl;
    a.download = 'lan3d_screenshot.png';
    a.click();
    toast('📷 Screenshot saqlandi: lan3d_screenshot.png');
  } catch(e) {
    toast('⚠️ Screenshot xatosi: ' + e.message);
  }
}

/* ==========================================================================
   2. Cisco IOS Config Eksport (.txt)
   ========================================================================== */
function generateCiscoConfig(devId) {
  const dev = devices.get(devId);
  if (!dev) return '';
  const t = dev.type;
  const now = new Date().toISOString().slice(0, 16).replace('T', ' ');
  let cfg = `!\n! Generated by LAN 3D Simulator\n! Date: ${now}\n! Device: ${dev.name} (${t})\n!\n`;

  if (t === 'router') {
    cfg += `hostname ${dev.name}\n!\n`;
    cfg += `no ip domain-lookup\n`;
    cfg += `ip routing\n!\n`;
    // Interfacelar
    const connectedConns = [...connections.values()].filter(c => c.a === devId || c.b === devId);
    connectedConns.forEach((c, i) => {
      const otherId = c.a === devId ? c.b : c.a;
      const other   = devices.get(otherId);
      cfg += `interface GigabitEthernet0/${i}\n`;
      cfg += ` description To_${other ? other.name.replace(/\s/g,'_') : otherId}\n`;
      cfg += ` ip address ${dev.ip} ${dev.mask}\n`;
      cfg += ` no shutdown\n!\n`;
    });
    cfg += `interface GigabitEthernet0/${connectedConns.length}\n description Management\n ip address ${dev.ip} ${dev.mask}\n no shutdown\n!\n`;
    cfg += `ip route 0.0.0.0 0.0.0.0 ${dev.gw || '0.0.0.0'}\n!\n`;
    cfg += `line con 0\n transport input none\n!\nend\n`;

  } else if (t === 'switch') {
    cfg += `hostname ${dev.name}\n!\n`;
    cfg += `no ip domain-lookup\n!\n`;
    cfg += `spanning-tree mode pvst\n!\n`;
    const connectedConns = [...connections.values()].filter(c => c.a === devId || c.b === devId);
    connectedConns.forEach((c, i) => {
      const otherId = c.a === devId ? c.b : c.a;
      const other   = devices.get(otherId);
      cfg += `interface FastEthernet0/${i + 1}\n`;
      cfg += ` description To_${other ? other.name.replace(/\s/g,'_') : otherId}\n`;
      cfg += ` switchport mode access\n`;
      cfg += ` switchport access vlan 1\n`;
      cfg += ` spanning-tree portfast\n`;
      cfg += ` no shutdown\n!\n`;
    });
    cfg += `interface Vlan1\n ip address ${dev.ip} ${dev.mask}\n no shutdown\n!\n`;
    cfg += `ip default-gateway ${dev.gw || '192.168.1.1'}\n!\n`;
    cfg += `line con 0\n!\nend\n`;

  } else {
    // PC/Laptop/Server uchun
    cfg += `! Host: ${dev.name}\n`;
    cfg += `! IP Address  : ${dev.ip}\n`;
    cfg += `! Subnet Mask : ${dev.mask}\n`;
    cfg += `! Gateway     : ${dev.gw}\n`;
    cfg += `! DNS         : ${dev.dns || '8.8.8.8'}\n`;
    cfg += `! MAC Address : ${dev.mac}\n`;
    cfg += `!\n! Network Interface Configuration:\n`;
    cfg += `!   ipconfig set LAN0 static ${dev.ip} ${dev.mask} ${dev.gw}\n`;
    cfg += `!\nend\n`;
  }
  return cfg;
}

function exportCiscoConfig(devId) {
  if (!devId) {
    // Barcha qurilmalar
    let fullCfg = '';
    devices.forEach(d => {
      fullCfg += generateCiscoConfig(d.id);
      fullCfg += '\n! ' + '='.repeat(60) + '\n\n';
    });
    downloadBlob('lan3d_full_config.txt', fullCfg);
    toast('📄 Barcha qurilmalar konfiguratsiyasi yuklandi');
  } else {
    const dev = devices.get(devId);
    const cfg = generateCiscoConfig(devId);
    downloadBlob(`${dev.name.replace(/\s/g,'_')}_config.txt`, cfg);
    toast(`📄 ${dev.name} konfiguratsiyasi yuklandi`);
  }
}

/* ==========================================================================
   3. Tarmoq Hisoboti (HTML)
   ========================================================================== */
function exportNetworkReport() {
  const now = new Date().toLocaleString('uz-UZ');
  const devRows = [...devices.values()].map(d => `
    <tr>
      <td>${d.name}</td>
      <td><span class="badge">${d.type}</span></td>
      <td class="mono">${d.ip}</td>
      <td class="mono">${d.mask}</td>
      <td class="mono">${d.gw}</td>
      <td class="mono">${d.mac}</td>
      <td>${d.modelName || d.modelKey || '—'}</td>
    </tr>
  `).join('');

  const connRows = [...connections.values()].map(c => {
    const a = devices.get(c.a), b = devices.get(c.b);
    return `
      <tr>
        <td>${a ? a.name : c.a}</td>
        <td>${b ? b.name : c.b}</td>
        <td>${c.cableType || 'auto'}</td>
        <td>${c.wireless ? '📶 Wireless' : '🔌 Wired'}</td>
        <td>${c.portA || '—'} ↔ ${c.portB || '—'}</td>
      </tr>
    `;
  }).join('');

  const html = `<!DOCTYPE html>
<html lang="uz">
<head>
<meta charset="UTF-8">
<title>Tarmoq Hisoboti — LAN 3D</title>
<style>
  body { font-family: Inter, sans-serif; background:#0D1117; color:#E6EDF3; margin:0; padding:24px; }
  h1 { color:#00FF87; margin-bottom:4px; }
  .meta { color:#8B949E; font-size:13px; margin-bottom:24px; }
  table { width:100%; border-collapse:collapse; margin-bottom:24px; }
  th { background:#21262D; padding:8px 12px; text-align:left; font-size:12px; color:#8B949E; }
  td { padding:8px 12px; border-bottom:1px solid #30363D; font-size:13px; }
  tr:hover td { background:rgba(255,255,255,0.03); }
  .mono { font-family:'JetBrains Mono',monospace; font-size:12px; }
  .badge { background:#21262D; padding:2px 8px; border-radius:4px; font-size:11px; }
  h2 { color:#38BDF8; font-size:16px; margin-top:32px; margin-bottom:8px; }
  .stats { display:flex; gap:24px; margin-bottom:24px; }
  .stat { background:#21262D; padding:12px 20px; border-radius:8px; }
  .stat-num { font-size:28px; font-weight:800; color:#00FF87; }
  .stat-lbl { font-size:12px; color:#8B949E; }
</style>
</head>
<body>
<h1>🌐 Tarmoq Hisoboti</h1>
<div class="meta">LAN 3D Simulator · Yaratildi: ${now}</div>
<div class="stats">
  <div class="stat"><div class="stat-num">${devices.size}</div><div class="stat-lbl">Qurilmalar</div></div>
  <div class="stat"><div class="stat-num">${connections.size}</div><div class="stat-lbl">Ulanishlar</div></div>
  <div class="stat"><div class="stat-num">${[...connections.values()].filter(c=>c.wireless).length}</div><div class="stat-lbl">Wireless</div></div>
</div>

<h2>Qurilmalar ro'yxati</h2>
<table>
  <thead><tr><th>Nomi</th><th>Turi</th><th>IP Manzil</th><th>Subnet Mask</th><th>Gateway</th><th>MAC</th><th>Model</th></tr></thead>
  <tbody>${devRows}</tbody>
</table>

<h2>Ulanishlar ro'yxati</h2>
<table>
  <thead><tr><th>Manba</th><th>Maqsad</th><th>Kabel</th><th>Tur</th><th>Portlar</th></tr></thead>
  <tbody>${connRows}</tbody>
</table>
</body>
</html>`;

  downloadBlob('lan3d_network_report.html', html, 'text/html');
  toast('📊 Tarmoq hisoboti yuklandi: lan3d_network_report.html');
}

/* ==========================================================================
   4. 2D SVG Topologiya Diagrammasi
   ========================================================================== */
function exportTopologySvg() {
  const W = 900, H = 700, PAD = 60;
  const devList = [...devices.values()];
  if (devList.length === 0) { toast('⚠️ Sahnada qurilma yo\'q!'); return; }

  // 3D pozitsiyalarni 2D ga o'tkazish
  const xs = devList.map(d => d.group.position.x);
  const zs = devList.map(d => d.group.position.z);
  const minX = Math.min(...xs), maxX = Math.max(...xs);
  const minZ = Math.min(...zs), maxZ = Math.max(...zs);
  const scaleX = maxX === minX ? 1 : (W - PAD*2) / (maxX - minX);
  const scaleZ = maxZ === minZ ? 1 : (H - PAD*2) / (maxZ - minZ);

  function toSvgX(x) { return PAD + (x - minX) * scaleX; }
  function toSvgY(z) { return PAD + (z - minZ) * scaleZ; }

  const COLORS = { router:'#A78BFA', switch:'#38BDF8', server:'#FFB454', desktop:'#6FE3C4', laptop:'#34D399', phone:'#EC4899', printer:'#FBBF24', tablet:'#60A5FA' };

  const connLines = [...connections.values()].map(c => {
    const a = devices.get(c.a), b = devices.get(c.b);
    if (!a || !b) return '';
    const x1 = toSvgX(a.group.position.x), y1 = toSvgY(a.group.position.z);
    const x2 = toSvgX(b.group.position.x), y2 = toSvgY(b.group.position.z);
    const stroke = c.wireless ? '#4FC7E8' : '#444';
    const dash   = c.wireless ? 'stroke-dasharray="6 4"' : '';
    return `<line x1="${x1.toFixed(1)}" y1="${y1.toFixed(1)}" x2="${x2.toFixed(1)}" y2="${y2.toFixed(1)}" stroke="${stroke}" stroke-width="2" ${dash} opacity="0.6"/>`;
  }).join('\n');

  const devNodes = devList.map(d => {
    const x = toSvgX(d.group.position.x), y = toSvgY(d.group.position.z);
    const col = COLORS[d.type] || '#fff';
    return `
      <circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="18" fill="${col}" fill-opacity="0.2" stroke="${col}" stroke-width="2"/>
      <text x="${x.toFixed(1)}" y="${(y+4).toFixed(1)}" text-anchor="middle" font-size="11" fill="${col}" font-family="Inter,sans-serif" font-weight="700">${d.type.slice(0,2).toUpperCase()}</text>
      <text x="${x.toFixed(1)}" y="${(y+34).toFixed(1)}" text-anchor="middle" font-size="10" fill="#E6EDF3" font-family="Inter,sans-serif">${escapeHtml(d.name)}</text>
      <text x="${x.toFixed(1)}" y="${(y+46).toFixed(1)}" text-anchor="middle" font-size="9" fill="#8B949E" font-family="JetBrains Mono,monospace">${d.ip}</text>
    `;
  }).join('\n');

  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
  <rect width="100%" height="100%" fill="#0D1117"/>
  <text x="20" y="26" font-size="14" fill="#6FE3C4" font-family="Inter,sans-serif" font-weight="800">🌐 LAN 3D — Network Topology Diagram</text>
  <text x="20" y="42" font-size="10" fill="#8B949E" font-family="Inter,sans-serif">${devices.size} qurilma · ${connections.size} ulanish · ${new Date().toLocaleString('uz-UZ')}</text>
  <g id="connections">${connLines}</g>
  <g id="devices">${devNodes}</g>
</svg>`;

  downloadBlob('lan3d_topology.svg', svg, 'image/svg+xml');
  toast('🗺️ 2D Topologiya diagrammasi yuklandi: lan3d_topology.svg');
}

/* ---------- Export Dropdown Ochish ---------- */
function openExportDropdown(e) {
  if (e && typeof e.stopPropagation === 'function') e.stopPropagation();
  ['topoMenu', 'roomMenu', 'cableMenu'].forEach(id => {
    const el = document.getElementById(id);
    if (el) el.classList.remove('show');
  });
  const dd = document.getElementById('exportDropdown');
  if (dd) dd.classList.toggle('show');
}

document.addEventListener('click', (e) => {
  const dd  = document.getElementById('exportDropdown');
  const btn = document.getElementById('exportBtn');
  if (dd && !dd.contains(e.target) && (!btn || !btn.contains(e.target))) {
    dd.classList.remove('show');
  }
});

if (typeof document !== 'undefined') {
  const initExportItems = () => {
    const dd = document.getElementById('exportDropdown');
    if (dd) {
      dd.querySelectorAll('.topo-item').forEach(item => {
        item.addEventListener('click', () => dd.classList.remove('show'));
      });
    }
  };
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initExportItems);
  } else {
    initExportItems();
  }
}
